[tool.black]

line-length = 110


[tool.pylint.format]

max-line-length=110

[tool.pylint."MESSAGES CONTROL"]

disable = '''
  bare-except,
  broad-exception-caught,
  broad-exception-raised,

  missing-function-docstring,
  missing-class-docstring,
  missing-module-docstring,
  fixme,

  line-too-long,
  too-few-public-methods,
  too-many-instance-attributes,
  too-many-arguments,
  too-many-locals,
  too-many-branches,
'''
