[tool.black]

line-length = 110
exclude = "node_modules/"


[tool.pylint.format]

max-line-length=110

[tool.pylint."MESSAGES CONTROL"]

disable = '''
  missing-function-docstring,
  missing-class-docstring,
  missing-module-docstring,
  fixme,
  too-many-lines,

  duplicate-code,
  line-too-long,
  too-few-public-methods,
  too-many-instance-attributes,
  too-many-arguments,
  too-many-locals,
  too-many-branches,
'''

[tool.vulture]

ignore_decorators = ["@app.*"]
ignore_names = ["LOAD_TRUNCATED_IMAGES", "ASC"]

[tool.pydeps]

max_bacon = 2
cluster = true
rmprefix = "pphoto."
exclude = [
  "*.test_*",
]
exclude_exact = [
  # Ignore empty modules with __init__.py
  "pphoto",
  "pphoto.annots",
  "pphoto.apps",
  "pphoto.data_model",
  "pphoto.db",
  "pphoto.file_mgmt",
  "pphoto.gallery",
  "pphoto.remote_jobs",
  # Following modules are supposed to be used everywhere
  "pphoto.data_model.base",
  "pphoto.utils",
  "pphoto.utils.files",
  "pphoto.db.connection",
  "pphoto.data_model.config",
]
