[tool.black]

line-length = 110
exclude = "node_modules/"


[tool.pylint.format]

max-line-length=110

[tool.pylint."MESSAGES CONTROL"]

disable = '''
  missing-function-docstring,
  missing-class-docstring,
  missing-module-docstring,
  fixme,

  line-too-long,
  too-few-public-methods,
  too-many-instance-attributes,
  too-many-arguments,
  too-many-locals,
  too-many-branches,
'''

[tool.vulture]

ignore_decorators = ["@app.*"]
ignore_names = ["LOAD_TRUNCATED_IMAGES"]
