// This file is auto-generated by @hey-api/openapi-ts

export type AggregateQuery = {
    query: SearchQuery;
};

export type AnnotationOverlayInterpolateLocation = {
    t: 'InterpolatedLocation';
    location: ManualLocation;
};

export type t = 'InterpolatedLocation';

export type AnnotationOverlayNoLocation = {
    t: 'NoLocation';
};

export type t2 = 'NoLocation';

export type DateCluster = {
    example_path_md5: string;
    example_path_extension: string;
    bucket_min: number;
    bucket_max: number;
    overfetched: boolean;
    min_timestamp: number;
    max_timestamp: number;
    avg_timestamp: number;
    total: number;
    group_by: DateClusterGroup;
};

export type DateClusterGroup = {
    address_name: string | null;
    country: string | null;
    camera: string | null;
    has_location: boolean | null;
};

export type DateClusterGroupBy = 'country' | 'camera' | 'has_location' | 'address_name';

export type DateClusterParams = {
    url: SearchQuery;
    group_by: Array<DateClusterGroupBy>;
    buckets: number;
};

export type DirectoryStats = {
    directory: string;
    total_images: number;
    has_location: number;
    has_timestamp: number;
    being_annotated: number;
    since: number | null;
    until: number | null;
};

export type ExceptionInfo = {
    exc_type: string | null;
    exc_val: string | null;
    exc_tb: Array<(string)> | null;
};

export type FaceFeatureRequest = {
    md5: string;
    extension: string;
};

export type FaceIdentifier = {
    md5: string;
    extension: string;
    position: Position;
};

export type FaceWithMeta = {
    position: Position;
    md5: string;
    extension: string;
    identity: string | null;
    skip_reason: IdentitySkipReason | null;
    embedding: Array<(number)>;
};

export type FacesResponse = {
    has_next_page: boolean;
    faces: Array<FaceWithMeta>;
    top_identities: Array<IdentityRowPayload>;
};

export type FoundLocation = {
    latitude: number;
    longitude: number;
    address: string;
};

export type GalleryPaging = {
    page?: number;
    paging?: number;
};

export type GalleryRequest = {
    query: SearchQuery;
    paging: GalleryPaging;
    sort: SortParams;
};

export type GetAddressRequest = {
    latitude: number;
    longitude: number;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type IdentityRowPayload = {
    identity: string;
    example_md5: string | null;
    example_extension: string | null;
    updates: number;
    last_update: number;
};

export type IdentitySkipReason = 'not_face' | 'not_poi';

export type Image = {
    md5: string;
    extension: string;
    date: string | null;
    date_transformed: boolean;
    tags: {
    [key: string]: (number);
} | null;
    classifications: string | null;
    address: ImageAddress;
    dependent_features_last_update: number;
    latitude: number | null;
    longitude: number | null;
    altitude: number | null;
    manual_features: Array<(string)>;
    being_annotated: boolean;
    camera: string | null;
    software: string | null;
    identities: Array<(string)>;
    version: number;
};

export type ImageAddress = {
    country: string | null;
    name: string | null;
    full: string | null;
};

export type ImageAggregation = {
    total: number;
    address: {
        [key: string]: (number);
    };
    tag: {
        [key: string]: (number);
    };
    classification: {
        [key: string]: (number);
    };
    cameras: {
        [key: string]: (number);
    };
    identities: {
        [key: string]: (number);
    };
};

export type ImageResponse = {
    has_next_page: boolean;
    omgs: Array<ImageWithMeta>;
    some_location: ManualLocation | null;
};

export type ImageSize = 'original' | 'medium' | 'preview';

export type ImageWithMeta = {
    omg: Image;
    predicted_location: PredictedLocation | null;
    paths: Array<PathSplit>;
};

export type JobDescription = {
    icon: string;
    total: string;
    id: number;
    type: string;
    replacements: string;
    time: number;
    latitude: number | null;
    longitude: number | null;
    query: MassLocationAndTextAnnotation_Output | Array<ManualIdentityClusterRequest_Output> | null;
    job: RemoteJob_bytes_;
    example_path_md5: string | null;
    example_path_extension: string | null;
};

export type JobProgressRequest = {
    state?: JobProgressState | null;
};

export type JobProgressState = {
    ts: number;
    t_total: number;
    t_finished: number;
    j_total: number;
    j_finished: number;
    j_waiting: number;
};

export type JobProgressStateResponse = {
    state: JobProgressState;
    diff: JobProgressState | null;
    eta_str: string | null;
};

export type LocClusterParams = {
    nw: LocPoint;
    se: LocPoint;
    url: SearchQuery;
    res: LocPoint;
    of?: number;
};

export type LocPoint = {
    latitude: number;
    longitude: number;
};

export type LocationBounds = {
    nw: LocPoint;
    se: LocPoint;
};

export type LocationCluster = {
    example_path_md5: string;
    example_path_extension: string;
    example_classification: string | null;
    size: number;
    address_name: string | null;
    address_country: string | null;
    tsfrom: number | null;
    tsto: number | null;
    top_left: LocPoint;
    bottom_right: LocPoint;
    position: LocPoint;
};

export type LocationQueryFixedLocation = {
    t: 'FixedLocation';
    location: ManualLocation;
    override: ManualLocationOverride;
};

export type t3 = 'FixedLocation';

export type ManualIdentityClusterRequest_Input = {
    identity: string | null;
    skip_reason: IdentitySkipReason | null;
    faces: Array<FaceIdentifier>;
};

export type ManualIdentityClusterRequest_Output = {
    identity: string | null;
    skip_reason: IdentitySkipReason | null;
    faces: Array<FaceIdentifier>;
};

export type ManualLocation = {
    latitude: number;
    longitude: number;
    address_name: string | null;
    address_country: string | null;
};

export type ManualLocationOverride = 'NoLocNoMan' | 'NoLocYeMan' | 'YeLocNoMan' | 'YeLocYeMan';

export type MapSearchResponse = {
    response: Array<FoundLocation> | null;
    error: string | null;
};

export type MassLocationAndTextAnnotation_Input = {
    t: 'MassLocAndTxt';
    query: SearchQuery;
    location: LocationQueryFixedLocation | AnnotationOverlayInterpolateLocation | AnnotationOverlayNoLocation;
    text: TextQueryFixedText;
    date: TransDate;
};

export type t4 = 'MassLocAndTxt';

export type MassLocationAndTextAnnotation_Output = {
    t: 'MassLocAndTxt';
    query: SearchQuery;
    location: LocationQueryFixedLocation | AnnotationOverlayInterpolateLocation | AnnotationOverlayNoLocation;
    text: TextQueryFixedText;
    date: TransDate;
};

export type PathSplit = {
    dir: string;
    file: string;
};

export type Position = {
    left: number;
    top: number;
    right: number;
    bottom: number;
};

export type PredictedLocation = {
    loc: LocPoint;
    earlier: ReferenceStats | null;
    later: ReferenceStats | null;
};

export type ProgressBarProgress = {
    desc: string | null;
    progress: number;
    total: number;
    rate: number | null;
    elapsed: number | null;
};

export type ReferenceStats = {
    distance_m: number;
    seconds: number;
};

export type RemoteJobType = 'mass_manual_annotation' | 'face_cluster_annotation';

export type RemoteJob_bytes_ = {
    id_: number;
    type_: RemoteJobType;
    total: number;
    finished_tasks: number;
    original_request: (Blob | File);
    created: string;
    last_update: string | null;
    example_path_md5: string | null;
    example_path_extension: string | null;
};

export type SearchQuery = {
    tag?: string;
    cls?: string;
    addr?: string;
    directory?: string;
    camera?: string;
    identity?: string | null;
    tsfrom?: number | null;
    tsto?: number | null;
    skip_with_location?: boolean;
    skip_being_annotated?: boolean;
    timestamp_trans?: string | null;
};

export type SortBy = 'TIMESTAMP' | 'RANDOM';

export type SortOrder = 'DESC' | 'ASC';

export type SortParams = {
    sort_by?: SortBy;
    order?: SortOrder;
};

export type State = {
    name: string;
    state: StateEnum;
    when: number;
    exception: ExceptionInfo | null;
};

export type StateEnum = 'initialized' | 'running' | 'finished' | 'unexpected finish' | 'error';

export type SystemStatus = {
    progress_bars: Array<[
        number,
        ProgressBarProgress
    ]>;
    current_state: {
        [key: string]: State;
    };
    t?: 'SystemStatus';
};

export type t5 = 'SystemStatus';

export type TextAnnotation = {
    description: string | null;
    tags: string | null;
};

export type TextAnnotationOverride = 'ExMan' | 'NoMan' | 'YeMan';

export type TextQueryFixedText = {
    t: 'FixedText';
    text: TextAnnotation;
    override: TextAnnotationOverride;
    loc_only: boolean;
};

export type t6 = 'FixedText';

export type TransDate = {
    t: 'TransDate';
    adjust_dates: boolean;
};

export type t7 = 'TransDate';

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type ImageEndpointGetData = {
    extension: string;
    hsh: string;
    position?: string | null;
    size: ImageSize;
};

export type ImageEndpointGetResponse = unknown;

export type LocationClustersEndpointPostData = {
    requestBody: LocClusterParams;
};

export type LocationClustersEndpointPostResponse = Array<LocationCluster>;

export type LocationBoundsEndpointPostData = {
    requestBody: SearchQuery;
};

export type LocationBoundsEndpointPostResponse = LocationBounds | null;

export type DateClustersEndpointPostData = {
    requestBody: DateClusterParams;
};

export type DateClustersEndpointPostResponse = Array<DateCluster>;

export type MassManualAnnotationEndpointPostData = {
    requestBody: MassLocationAndTextAnnotation_Input;
};

export type MassManualAnnotationEndpointPostResponse = number;

export type ManualIdentityAnnotationEndpointPostData = {
    requestBody: Array<ManualIdentityClusterRequest_Input>;
};

export type ManualIdentityAnnotationEndpointPostResponse = number;

export type FindLocationPostData = {
    req: string;
};

export type FindLocationPostResponse = MapSearchResponse;

export type JobProgressStatePostData = {
    requestBody: JobProgressRequest;
};

export type JobProgressStatePostResponse = JobProgressStateResponse;

export type RemoteJobsGetResponse = Array<JobDescription>;

export type SystemStatusGetResponse = SystemStatus;

export type GetAddressPostData = {
    requestBody: GetAddressRequest;
};

export type GetAddressPostResponse = ImageAddress;

export type MatchingDirectoriesPostData = {
    requestBody: SearchQuery;
};

export type MatchingDirectoriesPostResponse = Array<DirectoryStats>;

export type ImagePagePostData = {
    requestBody: GalleryRequest;
};

export type ImagePagePostResponse = ImageResponse;

export type FacesOnPagePostData = {
    requestBody: GalleryRequest;
};

export type FacesOnPagePostResponse = FacesResponse;

export type FaceFeaturesForImagePostData = {
    requestBody: FaceFeatureRequest;
};

export type FaceFeaturesForImagePostResponse = Array<FaceWithMeta>;

export type AggregateImagesPostData = {
    requestBody: AggregateQuery;
};

export type AggregateImagesPostResponse = ImageAggregation;

export type ReadIndexGetResponse = unknown;

export type ReadIndexGet1Response = unknown;

export type $OpenApiTs = {
    '/img/{size}/{hsh}.{extension}': {
        get: {
            req: ImageEndpointGetData;
            res: {
                /**
                 * photo
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/location_clusters': {
        post: {
            req: LocationClustersEndpointPostData;
            res: {
                /**
                 * Successful Response
                 */
                200: Array<LocationCluster>;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/bounds': {
        post: {
            req: LocationBoundsEndpointPostData;
            res: {
                /**
                 * Successful Response
                 */
                200: LocationBounds | null;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/date_clusters': {
        post: {
            req: DateClustersEndpointPostData;
            res: {
                /**
                 * Successful Response
                 */
                200: Array<DateCluster>;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/mass_manual_annotation': {
        post: {
            req: MassManualAnnotationEndpointPostData;
            res: {
                /**
                 * Successful Response
                 */
                200: number;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/manual_identity_annotation': {
        post: {
            req: ManualIdentityAnnotationEndpointPostData;
            res: {
                /**
                 * Successful Response
                 */
                200: number;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/map_search': {
        post: {
            req: FindLocationPostData;
            res: {
                /**
                 * Successful Response
                 */
                200: MapSearchResponse;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/job_progress_state': {
        post: {
            req: JobProgressStatePostData;
            res: {
                /**
                 * Successful Response
                 */
                200: JobProgressStateResponse;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/remote_jobs': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: Array<JobDescription>;
            };
        };
    };
    '/api/system_status': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: SystemStatus;
            };
        };
    };
    '/api/get_address': {
        post: {
            req: GetAddressPostData;
            res: {
                /**
                 * Successful Response
                 */
                200: ImageAddress;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/directories': {
        post: {
            req: MatchingDirectoriesPostData;
            res: {
                /**
                 * Successful Response
                 */
                200: Array<DirectoryStats>;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/images': {
        post: {
            req: ImagePagePostData;
            res: {
                /**
                 * Successful Response
                 */
                200: ImageResponse;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/faces': {
        post: {
            req: FacesOnPagePostData;
            res: {
                /**
                 * Successful Response
                 */
                200: FacesResponse;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/face': {
        post: {
            req: FaceFeaturesForImagePostData;
            res: {
                /**
                 * Successful Response
                 */
                200: Array<FaceWithMeta>;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/aggregate': {
        post: {
            req: AggregateImagesPostData;
            res: {
                /**
                 * Successful Response
                 */
                200: ImageAggregation;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
            };
        };
    };
    '/index.html': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
            };
        };
    };
};